name: Run Cucumber Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Install Maven
      run: |
        $MavenUrl = "https://downloads.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip"
        $MavenPath = "$env:GITHUB_WORKSPACE\maven"
        Invoke-WebRequest -Uri $MavenUrl -OutFile "maven.zip"
        Expand-Archive -Path "maven.zip" -DestinationPath $MavenPath
        Remove-Item -Force "maven.zip"
        $env:PATH += ";$MavenPath\apache-maven-3.8.4\bin"
      shell: pwsh

    - name: Display Java version
      run: java -version

    - name: Display Maven version
      run: mvn -version

    - name: Build with Maven
      run: mvn clean install

    - name: Run Cucumber Tests
      run: mvn test
