name: Run Cucumber Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Cucumber Tests
      run: mvn test
