name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Install Maven
      run: |
        curl -L https://downloads.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip -o maven.zip
        tar -xf maven.zip
        move apache-maven-3.8.4 C:\maven
        setx PATH "%PATH%;C:\maven\bin"
      shell: powershell

    - name: Display Java version
      run: java -version
      shell: powershell

    - name: Display Maven version
      run: mvn -version
      shell: powershell

    - name: Build with Maven
      run: mvn clean install
      shell: powershell

    - name: Run Cucumber Tests
      run: mvn test
      shell: powershell
