name: Run Cucumber Tests
#
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      shell: powershell

    - name: Run Cucumber Tests 
      run: mvn -X test
      shell: powershell
