name: Run Cucumber Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'
        cache: 'maven'
        check-latest: true
        components: 'maven'

    - name: Display Java version
      run: java -version

    - name: Display Maven version
      run: mvn -version

    - name: Build with Maven
      run: mvn clean install

    - name: Run Cucumber Tests
      run: mvn test
